baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
sectionPagesMenu = 'main'

[taxonomies]
    category = 'categories'

[params]
    [params.author]
        name        = "Authorz Name"
        email       = "Authorz Email"
        description = "Authorz Desc"

    [params.galleriesdeluxe]
        # One of dartsass or libsass.
        sass_transpiler = "libsass"
        [params.galleriesdeluxe.sassvars]
        #   At least one key-value pair must remain 
        #   uncommented (see my note in Obsidian)
            foo_bar = "abc123"

    [params.gallerydeluxe]
        shuffle     = false
        reverse     = true
        # default is false:
        enable_exif = true
        # my addition:
        enable_captions = true

[module]
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "content"
        target = "content"
    [[module.imports]]
        path = "github.com/bep/galleriesdeluxe"
